spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.35.43:5433/bnosoft
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: movie2025
    show-sql: 'true'
    hibernate:
      ddl-auto: none